jobs:
  ~chart: jobs
  runs:
    build-frontend:
      use: build
      with:
        imagePackage: frontend
        dockerfile: targets/frontend/Dockerfile
        secrets:
          npmTiptapToken:
            secretName: npm-tiptap
            secretKey: NPM_TIPTAP_TOKEN
    build-ingester:
      use: build
      with:
        imagePackage: ingester
        dockerfile: targets/ingester/Dockerfile
    build-alert:
      use: build
      with:
        imagePackage: alert
        dockerfile: targets/alert-cli/Dockerfile
    build-export:
      use: build
      with:
        imagePackage: export
        dockerfile: targets/export-elasticsearch/Dockerfile
    build-contributions:
      use: build
      with:
        imagePackage: contributions
        dockerfile: targets/contributions/Dockerfile
        buildArgs:
          NODE_ENV: production
          CDTN_API_URL: https://cdtn-api.fabrique.social.gouv.fr
    build-hasura:
      use: build
      with:
        imagePackage: hasura
        context: targets/hasura
